### ISSUE TITLE
error when using with multer's memory storage option

### ISSUE THREAD

**Issue by freeeal** [achingbrain/mongoose-crate-s3#6]
i’m using your mongoose-crate-s3 module to store uploaded images in s3, and meanwhile using the multer middleware to parse the multipart/form-data fields. Multer by default uses disk storage, but if I want to use the memory storage, i’m running into issues. namely, i get the following error: No file exists at C:\Users\Alan\AppData\Local\Temp.... i'm not really sure why this could be the case. the mongoose-crate-s3 module you created does work, however, with multer's diskStorage option.

**Comment by achingbrain** [comment]
I've never used Multer so I'm not sure what could cause interoperability problems.  Doesn't sound like they should be related though.

Could you put a simple app together that demonstrates the problem so I can take a look?

**Comment by freeeal** [comment]
Thanks for the prompt response.. here are some snippets:

upload view: https://gist.github.com/freeeal/0deab61f2cba51837531
book model: https://gist.github.com/freeeal/9726b8924d1432ac12b1
controller: https://gist.github.com/freeeal/fba90e760fb9d86611cf

The idea is that an admin user can navigate to the admin page and upload a book name, author name, and book cover image. This returns the aforementioned error.

**Comment by LinusU** [comment]
You are just sending `req.files.bookPhoto` right of to the `attach` function. The only reason it worked before was because it had a `path` property which was used.

As far as I can tell, `mongoose-crate-s3` only supports uploading from a file on disk, not from memory. This will than not work until the attach function is modified to support `{ buffer: _ }` in addition to `{ path: _ }`.

**Comment by freeeal** [comment]
@achingbrain -- do you have any suggestions for adding support for buffer objects for the attach function?

**Comment by LinusU** [comment]
It could work something like this:

```javascript
var fn, src

if (attachment.path) {
  fn = 'putFile'
  src = attachment.path
} else if (attachment.buffer) {
  fn = 'putBuffer'
  src = attachment.buffer
} else {
  throw new Error(...)
}

this._client[fn](src, ...)
```

`putFile` is currently used but [knox](https://github.com/Automattic/knox) supports `putBuffer` and `putStream` as well.
